#! /bin/sh

# AUTOSTART
sxhkd &
picom &
polybar &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d '󰖟 1' ' 2' '󰈮 3' ' 4' '󰎆 5' 6 7 8 9 10 

bspc config border_width         1
bspc config window_gap           5 
bspc config normal_border_color "#4c566a"
bspc config active_border_color "#1e1e1e"      
bspc config focused_border_color "#61afef"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
feh --bg-fill ~/Pictures/bg.jpg
# polybar --config=~/.config/polybar/config.ini primary

